[package]
name = "libkoompi"
version = "0.1.0"
authors = ["Ma veasna <maveasnalearntosolve@gmail>", "Hang leang <hangleang127@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9"
getset = "0.1"
udev = "0.5.1"
libmath = "0.2.1"
ascii = "1.0.0"
log = "0.4.13"
bitflags = "1.2.1"
futures = "0.1"
futures-cpupool = "0.1"
tokio-timer = "0.1"

[dependencies.error-chain]
version = "0.12.4"
default-features = false