[package]
name = "libkoompi"
version = "0.1.0"
authors = ["Ma veasna <maveasnalearntosolve@gmail>", "Hang leang <hangleang127@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9"
getset = "0.1"
serde = { version = "1.0.120", features = ["derive"] }
toml = "^0.5"
# network-manager = "0.11"